### PR TITLE
Add PHP date.timezone Environment Variable

### PR DESCRIPTION
**Pull request by indiegenus**

### CODE REVIEW

**Review by fabriciojs — CHANGES_REQUESTED** [review]
@indiegenus thanks for the PR!

Please notice by the instruction on contributing (https://github.com/kool-dev/docker-php#update-images-with-templates) - after you edited files on `template/` folder, please run `kool run template` and commit all the changes to each tag folder.

**Comment by indiegenus** [comment]
@fabriciojs - thanks for the pointer about contributing. I just committed updates from `kool run template`.

**Review by fabriciojs — CHANGES_REQUESTED** [review]
LGTM! Just one more thing, sorry I missed that in the first review:

we have a table of contents for documenting the available environment variables you could use on the README. We should add this new variable to that list as well.

**Comment by indiegenus** [comment]
@fabriciojs - good catch! README updated in PR.

**Review by fabriciojs — APPROVED** [review]
🚀 👏🏻

**Pull request merged**
